services:
  # Servidor HTTP simples
  http-server:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./test-data:/usr/share/nginx/html
    networks:
      - test-network

  # Servidor FTP
  ftp-server:
    image: stilliard/pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      - PUBLICHOST=localhost
      - FTP_USER_NAME=testuser
      - FTP_USER_PASS=testpass
      - FTP_USER_HOME=/home/testuser
    volumes:
      - ./test-data:/home/testuser
    networks:
      - test-network

  # Cliente 1 - HTTP requests
  client1:
    image: curlimages/curl:latest
    command: >
      sh -c "
        while true; do
          curl -s http://http-server/ > /dev/null;
          sleep 2;
        done
      "
    depends_on:
      - http-server
    networks:
      - test-network

  # Cliente 2 - HTTP requests (mais frequente)
  client2:
    image: curlimages/curl:latest
    command: >
      sh -c "
        while true; do
          curl -s http://http-server/ > /dev/null;
          sleep 1;
        done
      "
    depends_on:
      - http-server
    networks:
      - test-network

  # Cliente 3 - FTP requests
  client3:
    image: curlimages/curl:latest
    command: >
      sh -c "
        while true; do
          curl -s ftp://ftp-server/ > /dev/null;
          sleep 3;
        done
      "
    depends_on:
      - ftp-server
    networks:
      - test-network

  # Cliente 4 - Mixed requests
  client4:
    image: curlimages/curl:latest
    command: >
      sh -c "
        while true; do
          curl -s http://http-server/ > /dev/null;
          sleep 1;
          curl -s ftp://ftp-server/ > /dev/null;
          sleep 2;
        done
      "
    depends_on:
      - http-server
      - ftp-server
    networks:
      - test-network

  # Cliente 5 - Heavy HTTP load
  client5:
    image: curlimages/curl:latest
    command: >
      sh -c "
        while true; do
          for i in {1..5}; do
            curl -s http://http-server/ > /dev/null &
          done;
          wait;
          sleep 1;
        done
      "
    depends_on:
      - http-server
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
